export const LOAD_POSTS_REQUESTED = "LOAD_POSTS_REQUESTED";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAILED = "LOAD_POSTS_FAILED";

export const INSERT_POST_SUCCESS = "INSERT_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";